name: Build and Release on Tag

on:
  push: 
     tags:
      - 'v*'
      - 'Ver*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get release script
        run: git clone --depth 1 https://github.com/nabe-abk/adiary-release-tools __tools/

      - name: Run checker script
        run: __tools/checker.pl

      - name: Build
        run: __tools/release.sh

      - name: Delete Release
        continue-on-error: true
        run: gh release delete "${{github.ref_name}}"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Release
        run: gh release create "${{github.ref_name}}" *.tar.bz2 *.zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

