name: Build and Release on Tag

on:
  push: 
     tags:
      - 'v*'
      - 'Ver*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Version String
        run: |
          echo "${{github.ref_name}}" | perl -e 'print "VERSION=" . (<STDIN> =~ /^.*?(\d+\.\d+(?:\.\d+)?\w*)/ ? $1 : "") . "\n"' >> "$GITHUB_ENV"

      - name: Check Version
        run: |
          if [ "$VERSION" = "" ]; then
            echo "Version is not found!"
            exit 99
          fi

      - name: Get release script
        run: git clone --depth 1 https://github.com/nabe-abk/adiary-release-tools __tools/

      - name: Run checker script
        run: __tools/checker.pl

      - name: Build
        run: __tools/release.sh

      - name: Delete Release
        continue-on-error: true
        run: gh release delete "${{github.ref_name}}"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Release
        run: gh release create "${{github.ref_name}}" -t "Version $VERSION" -n "[Release note](https://adiary.adiary.jp/?&t=adiary::%e3%83%aa%e3%83%aa%e3%83%bc%e3%82%b9&q=$VERSION)." *.tar.bz2 *.zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

